robot_data:
  urdf: /examples/kuka_iiwa_arm/urdf/iiwa14_simplified_collision.urdf
  robot_type: kuka_iiwa

residual_detector:
  gain: 100.0
  include_friction_torque: true
  publish_channel: RESIDUAL_OBSERVER_STATE