classdef Kinematic < atlasParams.Base
  methods
    function obj = Kinematic(r)
      typecheck(r, 'Atlas');
      obj = obj@atlasParams.Base(r);
      % set all the body motion weights to zero
      for j = 1:numel(obj.body_motion)
        obj.body_motion(j).weight = 0;
      end
      obj.whole_body = struct('Kp', 160*ones(r.getNumPositions(), 1),...
                              'damping_ratio', 0.7,...
                              'Kd', zeros(r.getNumPositions(), 1),...
                              'w_qdd', 1e-3 * ones(r.getNumVelocities(), 1),...
                              'integrator', struct('gains', zeros(r.getNumPositions(), 1),...
                                                   'clamps', zeros(r.getNumPositions(), 1),...
                                                   'eta', 0.995),...
                              'qdd_bounds', struct('min', -100*ones(r.getNumVelocities(), 1),...
                                                   'max', 100*ones(r.getNumVelocities(), 1)));
      obj = obj.updateKd();
    end
  end
end



