robot:
  urdf: /drake/examples/kuka_iiwa_arm/urdf/iiwa14_simplified_collision.urdf
  # options are 
  # - FIXED
  # - ROLLPITCHYAW
  # - QUATERNION (although I don't think quaternion will work at the moment)
  floatingBaseType: FIXED

data:
  # the particle locations to have when adding a new contact points
  initialParticleLocations: /drake/examples/ContactParticleFilter/config/kuka_iiwa_contact_particle_filter_initial_particle_locations.out
  # the cells in mesh on which contact is allowed
  contactCells: /drake/examples/ContactParticleFilter/config/kuka_iiwa_contact_particle_filter_contact_cells.out


thresholds:
  addContactPointTimeout: 0.25
  removeContactPointTimeout: 0.25
  #add/remove thresholds should be the same
  addContactPointSquaredError: 500.0
  removeContactPointSquaredError: 500.0
  squaredErrorBoundForMostLikelyParticleAveraging: 10.0
  timeAboveThresholdToAddParticleSet: 0.2

motionModel:
  var: 0.001 #0.05
  varMin: 0.001 # 0.01
  varMax: 0.0025
  varMaxSquaredErrorCutoff: 10.0

measurementModel:
  var: 0.1

addParticleSet:
  multipleInitialSteps: False

numParticles: 50

debug:
  publishTrueResidual: True
  useTrueResidual: False
  # toggle these channels to determine whether to use true residual (provided by externa force)
  # or estimated residual
  residualChannel: "RESIDUAL_OBSERVER_STATE"
  # residualChannel: "RESIDUAL_ACTUAL"
  maxNumParticleSets: 1
  forceThreshold: 1.0 # deprecated: not sure what this actually gets used for . . .
  
# note this noise is not added to true residual published by externalForce
# it is only added internally before computing the various estimates . . .
noise:
  addNoise: False
  stddev: 0.1
  # maxNoise: 

vis:
  draw: False
  publish: True
  publishVisualizationData: True
  drawMostLikely: True
  drawParticles: True
  drawHistoricalMostLikely: False

solver:
  solverType: forcespro


externalForce:
  showActiveLinkEstimate: False
  publishTrueResidual: False

# this is the haddadin method
twoStepEstimator:
  computeEstimate: True
  visualize: True
  showContactRay: True
  # whether or not externalforce.py should be providing information about
  # which links actually have contact
  provideLinkContactInfo: False
  publishChannel: TWO_STEP_ESTIMATOR
  residualThresholdForContact: 1


# options for the proposal distribution
proposal:
  # fraction of particles that will be sampled with standard motion model
  # the remaining fraction will be sampled around the historical most likely point
  normalFraction: 0.9
  normal:
    variance: 0.001 # 0.01

  historical:
    variance: 0.00015 # 0.01
